[package]
name = "del-msh-bvh-cudarc-kernel"
description = "hogehoge"
# version.workspace = true
# edition.workspace = true
# license.workspace = true

[dependencies]

[build-dependencies]
bindgen_cuda = "0.1.5"
